/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mycashbank.Interfaz;

/**
 *
 * @author dieza
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelSeparador = new javax.swing.JLabel();
        jButtonAreaClientes1 = new javax.swing.JButton();
        jButtonAreaTrabajadores1 = new javax.swing.JButton();
        jLabelIconoBanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(115, 198, 182));
        jPanel1.setForeground(new java.awt.Color(115, 198, 182));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(851, 638));

        jLabel1.setBackground(new java.awt.Color(60, 63, 65));
        jLabel1.setFont(new java.awt.Font("Libel Suit Rg", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(14, 102, 85));
        jLabel1.setText("MyCash Bank");
        jLabel1.setMaximumSize(new java.awt.Dimension(201, 59));
        jLabel1.setMinimumSize(new java.awt.Dimension(201, 59));
        jLabel1.setPreferredSize(new java.awt.Dimension(201, 59));

        jLabelSeparador.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelSeparador.setForeground(new java.awt.Color(187, 187, 187));
        jLabelSeparador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Separador.png"))); // NOI18N

        jButtonAreaClientes1.setBackground(new java.awt.Color(14, 102, 85));
        jButtonAreaClientes1.setFont(new java.awt.Font("Caviar Dreams", 1, 20)); // NOI18N
        jButtonAreaClientes1.setForeground(new java.awt.Color(11, 83, 69));
        jButtonAreaClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconAreaCliente.png"))); // NOI18N
        jButtonAreaClientes1.setText("Area de Clientes");
        jButtonAreaClientes1.setBorderPainted(false);
        jButtonAreaClientes1.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonAreaClientes1.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonAreaClientes1.setOpaque(false);
        jButtonAreaClientes1.setPreferredSize(new java.awt.Dimension(215, 48));

        jButtonAreaTrabajadores1.setBackground(new java.awt.Color(14, 102, 85));
        jButtonAreaTrabajadores1.setFont(new java.awt.Font("Caviar Dreams", 1, 20)); // NOI18N
        jButtonAreaTrabajadores1.setForeground(new java.awt.Color(11, 83, 69));
        jButtonAreaTrabajadores1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconAreaTrabajadores.png"))); // NOI18N
        jButtonAreaTrabajadores1.setText("Area de Trabajadores");
        jButtonAreaTrabajadores1.setBorderPainted(false);
        jButtonAreaTrabajadores1.setMaximumSize(new java.awt.Dimension(271, 48));
        jButtonAreaTrabajadores1.setMinimumSize(new java.awt.Dimension(271, 48));
        jButtonAreaTrabajadores1.setOpaque(false);
        jButtonAreaTrabajadores1.setPreferredSize(new java.awt.Dimension(271, 48));

        jLabelIconoBanco.setForeground(new java.awt.Color(187, 187, 187));
        jLabelIconoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabelSeparador))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(jLabelIconoBanco)
                                                                .addGap(15, 15, 15))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jButtonAreaClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonAreaTrabajadores1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelIconoBanco))
                                .addGap(14, 14, 14)
                                .addComponent(jLabelSeparador)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButtonAreaClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonAreaTrabajadores1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(448, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, 840, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButtonAreaClientes1;
    private javax.swing.JButton jButtonAreaTrabajadores1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelIconoBanco;
    private javax.swing.JLabel jLabelSeparador;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration
}
