/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author dam1a
 */
public class InterfazTrabajadores extends javax.swing.JFrame {

    /**
     * Creates new form InterfazTrabajadores
     */
    public InterfazTrabajadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabelIconoBanco1 = new javax.swing.JLabel();
        jLabelSeparador5 = new javax.swing.JLabel();
        jLabelSeparador7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLogoTrabajadores = new javax.swing.JLabel();
        jButtonAbrirCuenta = new javax.swing.JButton();
        jButtonEliminarCuenta = new javax.swing.JButton();
        jButtonModificarCuenta = new javax.swing.JButton();
        jButtonConsultarCuenta = new javax.swing.JButton();
        jButtonVolverMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(115, 198, 182));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(851, 638));

        jLabelIconoBanco1.setForeground(new java.awt.Color(187, 187, 187));
        jLabelIconoBanco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon.png"))); // NOI18N

        jLabelSeparador5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelSeparador5.setForeground(new java.awt.Color(187, 187, 187));
        jLabelSeparador5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Separador.png"))); // NOI18N

        jLabelSeparador7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelSeparador7.setForeground(new java.awt.Color(187, 187, 187));
        jLabelSeparador7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Separador.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N

        jLabelLogoTrabajadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoApartadoTrabajadores.png"))); // NOI18N

        jButtonAbrirCuenta.setBackground(new java.awt.Color(14, 102, 85));
        jButtonAbrirCuenta.setFont(new java.awt.Font("Caviar Dreams", 1, 16)); // NOI18N
        jButtonAbrirCuenta.setForeground(new java.awt.Color(11, 83, 69));
        jButtonAbrirCuenta.setText("Abrir Cuenta");
        jButtonAbrirCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonAbrirCuenta.setContentAreaFilled(false);
        jButtonAbrirCuenta.setFocusPainted(false);
        jButtonAbrirCuenta.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonAbrirCuenta.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonAbrirCuenta.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonAbrirCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAbrirCuentaActionPerformed(evt);
            }
        });

        jButtonEliminarCuenta.setBackground(new java.awt.Color(14, 102, 85));
        jButtonEliminarCuenta.setFont(new java.awt.Font("Caviar Dreams", 1, 16)); // NOI18N
        jButtonEliminarCuenta.setForeground(new java.awt.Color(11, 83, 69));
        jButtonEliminarCuenta.setText("Eliminar Cuenta");
        jButtonEliminarCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonEliminarCuenta.setContentAreaFilled(false);
        jButtonEliminarCuenta.setFocusPainted(false);
        jButtonEliminarCuenta.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonEliminarCuenta.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonEliminarCuenta.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonEliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarCuentaActionPerformed(evt);
            }
        });

        jButtonModificarCuenta.setBackground(new java.awt.Color(14, 102, 85));
        jButtonModificarCuenta.setFont(new java.awt.Font("Caviar Dreams", 1, 16)); // NOI18N
        jButtonModificarCuenta.setForeground(new java.awt.Color(11, 83, 69));
        jButtonModificarCuenta.setText("Modificar Cuenta");
        jButtonModificarCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonModificarCuenta.setContentAreaFilled(false);
        jButtonModificarCuenta.setFocusPainted(false);
        jButtonModificarCuenta.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonModificarCuenta.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonModificarCuenta.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonModificarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCuentaActionPerformed(evt);
            }
        });

        jButtonConsultarCuenta.setBackground(new java.awt.Color(14, 102, 85));
        jButtonConsultarCuenta.setFont(new java.awt.Font("Caviar Dreams", 1, 16)); // NOI18N
        jButtonConsultarCuenta.setForeground(new java.awt.Color(11, 83, 69));
        jButtonConsultarCuenta.setText("Consultar Cuenta");
        jButtonConsultarCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonConsultarCuenta.setContentAreaFilled(false);
        jButtonConsultarCuenta.setFocusPainted(false);
        jButtonConsultarCuenta.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonConsultarCuenta.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonConsultarCuenta.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonConsultarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarCuentaActionPerformed(evt);
            }
        });

        jButtonVolverMenu.setBackground(new java.awt.Color(14, 102, 85));
        jButtonVolverMenu.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        jButtonVolverMenu.setForeground(new java.awt.Color(11, 83, 69));
        jButtonVolverMenu.setText("Volver al Menú");
        jButtonVolverMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonVolverMenu.setContentAreaFilled(false);
        jButtonVolverMenu.setFocusPainted(false);
        jButtonVolverMenu.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonVolverMenu.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonVolverMenu.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelLogoTrabajadores)
                        .addGap(405, 405, 405)
                        .addComponent(jLabelIconoBanco1)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelSeparador7)
                        .addComponent(jLabelSeparador5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonConsultarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAbrirCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEliminarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonModificarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIconoBanco1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLogoTrabajadores)))
                .addGap(18, 18, 18)
                .addComponent(jLabelSeparador7)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAbrirCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addComponent(jButtonVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSeparador5)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAbrirCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAbrirCuentaActionPerformed

    }//GEN-LAST:event_jButtonAbrirCuentaActionPerformed

    private void jButtonEliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEliminarCuentaActionPerformed

    private void jButtonModificarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarCuentaActionPerformed

    private void jButtonConsultarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarCuentaActionPerformed

    private void jButtonVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverMenuActionPerformed
        this.setVisible(false);
        InterfazPrincipal iPrincipal = new InterfazPrincipal();
        iPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazTrabajadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazTrabajadores().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAbrirCuenta;
    private javax.swing.JButton jButtonConsultarCuenta;
    private javax.swing.JButton jButtonEliminarCuenta;
    private javax.swing.JButton jButtonModificarCuenta;
    private javax.swing.JButton jButtonVolverMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelIconoBanco1;
    private javax.swing.JLabel jLabelLogoTrabajadores;
    private javax.swing.JLabel jLabelSeparador5;
    private javax.swing.JLabel jLabelSeparador7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
