/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author dam1a
 */
public class InterfazClientes extends javax.swing.JFrame {

    /**
     * Creates new form InterfazClientes
     */
    public InterfazClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonAreaClientes1 = new javax.swing.JButton();
        jButtonAreaTrabajadores1 = new javax.swing.JButton();
        jLabelIconoBanco = new javax.swing.JLabel();
        jLabelSeparador2 = new javax.swing.JLabel();
        jLabelSeparador3 = new javax.swing.JLabel();
        jLabelSeparador4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelIconoBanco1 = new javax.swing.JLabel();
        jLabelSeparador5 = new javax.swing.JLabel();
        jLabelSeparador7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLogoClientes = new javax.swing.JLabel();
        jLabelSaldoTotalTexto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelSaldoTotal = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonConsultarBalance = new javax.swing.JButton();
        jButtonRealizarTransaccion = new javax.swing.JButton();
        jButtonConsultarDatosCuenta1 = new javax.swing.JButton();
        jButtonConsultarMovimientos = new javax.swing.JButton();
        jButtonVolverMenu = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(115, 198, 182));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(851, 638));

        jButtonAreaClientes1.setBackground(new java.awt.Color(14, 102, 85));
        jButtonAreaClientes1.setFont(new java.awt.Font("Caviar Dreams", 1, 20)); // NOI18N
        jButtonAreaClientes1.setForeground(new java.awt.Color(11, 83, 69));
        jButtonAreaClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconAreaCliente.png"))); // NOI18N
        jButtonAreaClientes1.setText("Area de Clientes");
        jButtonAreaClientes1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonAreaClientes1.setContentAreaFilled(false);
        jButtonAreaClientes1.setFocusPainted(false);
        jButtonAreaClientes1.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonAreaClientes1.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonAreaClientes1.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonAreaClientes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAreaClientes1ActionPerformed(evt);
            }
        });

        jButtonAreaTrabajadores1.setBackground(new java.awt.Color(14, 102, 85));
        jButtonAreaTrabajadores1.setFont(new java.awt.Font("Caviar Dreams", 1, 20)); // NOI18N
        jButtonAreaTrabajadores1.setForeground(new java.awt.Color(11, 83, 69));
        jButtonAreaTrabajadores1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconAreaTrabajadores.png"))); // NOI18N
        jButtonAreaTrabajadores1.setText("Area de Trabajadores");
        jButtonAreaTrabajadores1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonAreaTrabajadores1.setContentAreaFilled(false);
        jButtonAreaTrabajadores1.setFocusPainted(false);
        jButtonAreaTrabajadores1.setMaximumSize(new java.awt.Dimension(271, 48));
        jButtonAreaTrabajadores1.setMinimumSize(new java.awt.Dimension(271, 48));
        jButtonAreaTrabajadores1.setPreferredSize(new java.awt.Dimension(271, 48));
        jButtonAreaTrabajadores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAreaTrabajadores1ActionPerformed(evt);
            }
        });

        jLabelIconoBanco.setForeground(new java.awt.Color(187, 187, 187));
        jLabelIconoBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon.png"))); // NOI18N

        jLabelSeparador2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelSeparador2.setForeground(new java.awt.Color(187, 187, 187));
        jLabelSeparador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Separador.png"))); // NOI18N

        jLabelSeparador3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelSeparador3.setForeground(new java.awt.Color(187, 187, 187));
        jLabelSeparador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Separador.png"))); // NOI18N
        jLabelSeparador3.setMaximumSize(new java.awt.Dimension(788, 5));
        jLabelSeparador3.setMinimumSize(new java.awt.Dimension(788, 5));
        jLabelSeparador3.setPreferredSize(new java.awt.Dimension(788, 5));

        jLabelSeparador4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelSeparador4.setForeground(new java.awt.Color(187, 187, 187));
        jLabelSeparador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Separador.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelIconoBanco)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButtonAreaClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAreaTrabajadores1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelSeparador4)
                    .addComponent(jLabelSeparador2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSeparador3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIconoBanco)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelSeparador4)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAreaClientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAreaTrabajadores1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabelSeparador3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(jLabelSeparador2)
                .addGap(29, 29, 29))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(115, 198, 182));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(851, 638));

        jLabelIconoBanco1.setForeground(new java.awt.Color(187, 187, 187));
        jLabelIconoBanco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/icon.png"))); // NOI18N

        jLabelSeparador5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelSeparador5.setForeground(new java.awt.Color(187, 187, 187));
        jLabelSeparador5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Separador.png"))); // NOI18N

        jLabelSeparador7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelSeparador7.setForeground(new java.awt.Color(187, 187, 187));
        jLabelSeparador7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Separador.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logo.png"))); // NOI18N

        jLabelLogoClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/logoClientes.png"))); // NOI18N

        jLabelSaldoTotalTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSaldoTotalTexto.setForeground(new java.awt.Color(17, 122, 101));
        jLabelSaldoTotalTexto.setText("Saldo Total:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(19, 141, 117));
        jLabel4.setText("Seleccion de Cuenta:");

        jLabelSaldoTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSaldoTotal.setForeground(new java.awt.Color(17, 122, 101));
        jLabelSaldoTotal.setText("?????€");

        jComboBox1.setBackground(new java.awt.Color(69, 179, 157));
        jComboBox1.setForeground(new java.awt.Color(11, 83, 69));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(17, 122, 101));
        jLabel5.setText("Bienvenido (Nombre + Apellidos del Cliente)");

        jButtonConsultarBalance.setBackground(new java.awt.Color(14, 102, 85));
        jButtonConsultarBalance.setFont(new java.awt.Font("Caviar Dreams", 1, 16)); // NOI18N
        jButtonConsultarBalance.setForeground(new java.awt.Color(11, 83, 69));
        jButtonConsultarBalance.setText("Consultar Balance");
        jButtonConsultarBalance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonConsultarBalance.setContentAreaFilled(false);
        jButtonConsultarBalance.setFocusPainted(false);
        jButtonConsultarBalance.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonConsultarBalance.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonConsultarBalance.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonConsultarBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarBalanceActionPerformed(evt);
            }
        });

        jButtonRealizarTransaccion.setBackground(new java.awt.Color(14, 102, 85));
        jButtonRealizarTransaccion.setFont(new java.awt.Font("Caviar Dreams", 1, 16)); // NOI18N
        jButtonRealizarTransaccion.setForeground(new java.awt.Color(11, 83, 69));
        jButtonRealizarTransaccion.setText("Realizar Transacción");
        jButtonRealizarTransaccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonRealizarTransaccion.setContentAreaFilled(false);
        jButtonRealizarTransaccion.setFocusPainted(false);
        jButtonRealizarTransaccion.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonRealizarTransaccion.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonRealizarTransaccion.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonRealizarTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRealizarTransaccionActionPerformed(evt);
            }
        });

        jButtonConsultarDatosCuenta1.setBackground(new java.awt.Color(14, 102, 85));
        jButtonConsultarDatosCuenta1.setFont(new java.awt.Font("Caviar Dreams", 1, 16)); // NOI18N
        jButtonConsultarDatosCuenta1.setForeground(new java.awt.Color(11, 83, 69));
        jButtonConsultarDatosCuenta1.setText("Ver Datos de Cuenta");
        jButtonConsultarDatosCuenta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonConsultarDatosCuenta1.setContentAreaFilled(false);
        jButtonConsultarDatosCuenta1.setFocusPainted(false);
        jButtonConsultarDatosCuenta1.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonConsultarDatosCuenta1.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonConsultarDatosCuenta1.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonConsultarDatosCuenta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarDatosCuenta1ActionPerformed(evt);
            }
        });

        jButtonConsultarMovimientos.setBackground(new java.awt.Color(14, 102, 85));
        jButtonConsultarMovimientos.setFont(new java.awt.Font("Caviar Dreams", 1, 16)); // NOI18N
        jButtonConsultarMovimientos.setForeground(new java.awt.Color(11, 83, 69));
        jButtonConsultarMovimientos.setText("Movimientos");
        jButtonConsultarMovimientos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonConsultarMovimientos.setContentAreaFilled(false);
        jButtonConsultarMovimientos.setFocusPainted(false);
        jButtonConsultarMovimientos.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonConsultarMovimientos.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonConsultarMovimientos.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonConsultarMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarMovimientosActionPerformed(evt);
            }
        });

        jButtonVolverMenu.setBackground(new java.awt.Color(14, 102, 85));
        jButtonVolverMenu.setFont(new java.awt.Font("Caviar Dreams", 1, 14)); // NOI18N
        jButtonVolverMenu.setForeground(new java.awt.Color(11, 83, 69));
        jButtonVolverMenu.setText("Volver al Menú");
        jButtonVolverMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 83, 69), 2));
        jButtonVolverMenu.setContentAreaFilled(false);
        jButtonVolverMenu.setFocusPainted(false);
        jButtonVolverMenu.setMaximumSize(new java.awt.Dimension(215, 48));
        jButtonVolverMenu.setMinimumSize(new java.awt.Dimension(215, 48));
        jButtonVolverMenu.setPreferredSize(new java.awt.Dimension(215, 48));
        jButtonVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelLogoClientes)
                                .addGap(405, 405, 405)
                                .addComponent(jLabelIconoBanco1)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelSeparador7)
                                .addComponent(jLabelSeparador5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabelSaldoTotalTexto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabelSaldoTotal)
                            .addGap(61, 61, 61))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jButtonConsultarBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(251, 251, 251)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonConsultarMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConsultarDatosCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRealizarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel5)
                    .addContainerGap(399, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIconoBanco1)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelLogoClientes)))
                .addGap(18, 18, 18)
                .addComponent(jLabelSeparador7)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSaldoTotalTexto)
                    .addComponent(jLabelSaldoTotal))
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonConsultarBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRealizarTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultarMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonConsultarDatosCuenta1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jButtonVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSeparador5)
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(jLabel5)
                    .addContainerGap(395, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAreaClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAreaClientes1ActionPerformed

    }//GEN-LAST:event_jButtonAreaClientes1ActionPerformed

    private void jButtonAreaTrabajadores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAreaTrabajadores1ActionPerformed

    }//GEN-LAST:event_jButtonAreaTrabajadores1ActionPerformed

    private void jButtonConsultarBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarBalanceActionPerformed

    }//GEN-LAST:event_jButtonConsultarBalanceActionPerformed

    private void jButtonRealizarTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRealizarTransaccionActionPerformed

    }//GEN-LAST:event_jButtonRealizarTransaccionActionPerformed

    private void jButtonConsultarDatosCuenta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarDatosCuenta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarDatosCuenta1ActionPerformed

    private void jButtonConsultarMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarMovimientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConsultarMovimientosActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverMenuActionPerformed
        this.setVisible(false);
        InterfazPrincipal iPrincipal = new InterfazPrincipal();
        iPrincipal.setVisible(true);
    }//GEN-LAST:event_jButtonVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazClientes().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAreaClientes1;
    private javax.swing.JButton jButtonAreaTrabajadores1;
    private javax.swing.JButton jButtonConsultarBalance;
    private javax.swing.JButton jButtonConsultarDatosCuenta1;
    private javax.swing.JButton jButtonConsultarMovimientos;
    private javax.swing.JButton jButtonRealizarTransaccion;
    private javax.swing.JButton jButtonVolverMenu;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelIconoBanco;
    private javax.swing.JLabel jLabelIconoBanco1;
    private javax.swing.JLabel jLabelLogoClientes;
    private javax.swing.JLabel jLabelSaldoTotal;
    private javax.swing.JLabel jLabelSaldoTotalTexto;
    private javax.swing.JLabel jLabelSeparador2;
    private javax.swing.JLabel jLabelSeparador3;
    private javax.swing.JLabel jLabelSeparador4;
    private javax.swing.JLabel jLabelSeparador5;
    private javax.swing.JLabel jLabelSeparador7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
